### ISSUE TITLE
Pouvoir se créer un profil utilisateur.

### ISSUE THREAD

**Issue by MaelHin** [majeanlea/projet-angular-miage#11]
Un profil utilisateur doit être composé à minima d'un nom d'utilisateur, d'un nom et d'un prénom.

**Comment by jeansordes** [comment]
On va déplacer cette fonctionnalité pour qu'on puisse se créer un compte uniquement lors :
- de la création d'un événement
- d'un vote pour un événement

On demande un pseudo lors de ces 2 événements, si le pseudo est inconnu, on créé un compte, et on amène la personne sur une page où elle peut ajouter les détails ("Nom" et "Prénom") ou bien revenir en arrière pour modifier le pseudo qu'elle a renseigné
