### ISSUE TITLE
lier l'utilisateur a l'évenement durant la création d'un évènement OU lors d'un vote

### ISSUE THREAD

**Issue by leamau** [majeanlea/projet-angular-miage#24]

**Comment by jeansordes** [comment]
ça veut dire qu'on demande juste un pseudo à l'utilisateur, si ce pseudo existe déjà, chouette, on met alors le numéro utilisateur dans la création de l'événement (ou du vote), sinon, on redirige l'utilisateur vers la page `/new-user` (et on met en attente l'envoie du formulaire le temps de voir si l'utilisateur souhaite créer l'utilisateur ou s'il souhaite revenir en arrière et changer de pseudo)

Pour la partie création d'utilisateur, voir l'issue #11
